<?php if(count($this->getItems())):?>
<?php 
	$_filters = Mage::getSingleton('Mage_Catalog_Block_Layer_State')->getActiveFilters();
	$_filtersCount = count($_filters);
?>
    <ol>
        <?php foreach ($this->getItems() as $_item):?>
            <li>

                <em class="checkbox"></em>

                <?php if ($_item->getCount() > 0): ?>
                    <a <?php if($_filtersCount>1) echo 'rel="nofollow" '; ?> href="<?php echo $this->urlEscape($_item->getUrl()) ?>">
                        <?php echo $_item->getLabel() ?>
                    </a>
                <?php else: echo $_item->getLabel() ?>
                <?php endif; ?>

                <?php if ($this->shouldDisplayProductCount()): ?>
                    <span class="filter_count">(<?php echo $_item->getCount() ?>)</span>
                <?php endif; ?>

            </li>
        <?php endforeach ?>
    </ol>
<?php endif;?>