<div class="footer-container">
    <div class="footer">

        <div class="subscribe">
            <div class="subscribe-content">
                <?php echo $this->getChildHtml('footer.newsletter') ?>
                <div class="community">
                    <img src="/skin/frontend/beingformal/default/images/linshi.jpg">
                </div>
            </div>
        </div>

        <div class="links">
            <dl>
                <dd>Products Map</dd>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
            </dl>
            <dl>
                <dd>Products Map</dd>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
            </dl>
            <dl>
                <dd>Products Map</dd>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
            </dl>
            <dl>
                <dd>Products Map</dd>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
            </dl>
            <dl>
                <dd>Products Map</dd>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
                <dt><a href="">Product A-Z</a></dt>
            </dl>
        </div>

        <ul class="footer_links">
            <li><a href="">About Us</a></li><li><a href="">About Us</a></li><li><a href="">About Us</a></li><li><a href="">About Us</a></li><li><a href="">About Us</a></li><li><a href="">About Us</a></li>
        </ul>

        <p class="copyright">www.beingformal.com.au Copyright &copy; 2005-2017 promworld international limited. All Rights Reserved.</p>

        <p class="payments"><img src="/skin/frontend/beingformal/default/images/payments.jpg"></p>

    </div>
</div>




<?php echo $this->getLayout()->createBlock('catalog/product_list')->setTemplate('page/html/js.phtml')->toHtml(); ?>