<div class="footer-container">
    <div class="footer">

        <div class="subscribe">
            <div class="subscribe-content">
                <?php echo $this->getChildHtml('footer.newsletter') ?>
                <div class="community">
                    <img src="/skin/frontend/beingformal/default/images/linshi.jpg">
                </div>
            </div>
        </div>

        <div class="links">
            <dl>
                <dd>Products Map</dd>
                <dt><a href="/mostpopular/">Product A-Z</a></dt>
                <dt><a href="/helpcenter/popular_searches.html">Popular Searches</a></dt>
                <dt><a href="/helpcenter/fabric.html">Fabric</a></dt>
            </dl>
            <dl>
                <dd>Shipping & Returns</dd>
                <dt><a href="/helpcenter/main_shipping_methods.html">Main Shipping Methods</a></dt>
                <dt><a href="/helpcenter/dropshipping.html">Dropshipping</a></dt>
            </dl>
            <dl>
                <dd>Services & Support</dd>
                <dt><a href="/helpcenter/social_cooperation.html">Social Cooperation</a></dt>
                <dt><a href="/helpcenter/cancellation_returnpolicy.html">Cancellation Returnpolicy</a></dt>
            </dl>
            <dl>
                <dd>Need To Know</dd>
                <dt><a href="/helpcenter/size_chart.html">Size Chart</a></dt>
                <dt><a href="/helpcenter/your_own_dresses.html">Your Own Dresses</a></dt>
                <dt><a href="/helpcenter/vip_discount.html">Vip Discount</a></dt>
                <dt><a href="/helpcenter/shipping_time.html">Shipping Time</a></dt>
                <dt><a href="/helpcenter/payment_methods.html">Payment Methods</a></dt>
            </dl>
            <dl>
                <dd>Business</dd>
                <dt><a href="helpcenter/our_story.html">Our Story</a></dt>
                <dt><a href="helpcenter/our_customer_show.html">Our Customer Show</a></dt>
                <dt><a href="helpcenter/contactus.html">Contact Us</a></dt>
            </dl>
        </div>

        <ul class="footer_links">
            <li><a href="/helpcenter/aboutus.html">About Us</a></li>
            <li><a href="">Testimonials</a></li>
            <li><a href="">Terms of Use</a></li>
            <li><a href="">Privacy Policy</a></li>
            <li><a href="/catalog/seo_sitemap/category/">Sitemap</a></li>
            <li><a href="">Copyright</a></li>
        </ul>

        <p class="copyright">www.beingformal.com.au Copyright &copy; 2005-2017 promworld international limited. All Rights Reserved.</p>

        <p class="payments"><img src="/skin/frontend/beingformal/default/images/payments.jpg"></p>

    </div>
</div>




<?php echo $this->getLayout()->createBlock('catalog/product_list')->setTemplate('page/html/js.phtml')->toHtml(); ?>