<script type="text/javascript" data-name="pub-js">
    function countdown(text_day,id,theyear,themonth,theday,thehour,themin,thesec){
        var textday = text_day;
        var id=id;
        var yr=theyear;
        var mo=themonth;
        var da=theday;
        var ho=thehour;
        var mi=themin;
        var se=thesec;
        var montharray=new Array("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec");
        var today=new Date();
        var todayy=today.getYear();
        if (todayy < 1000)
            todayy+=1900;
        var todaym=today.getMonth();
        var todayd=today.getDate();
        var todayh=today.getHours();
        var todaymin=today.getMinutes();
        var todaysec=today.getSeconds();
        var todaystring=montharray[todaym]+" "+todayd+", "+todayy+" "+todayh+":"+todaymin+":"+todaysec;
        futurestring=montharray[mo-1]+" "+da+", "+yr+" "+ho+":"+mi+":"+se;
        dd=Date.parse(futurestring)-Date.parse(todaystring);
        dday=Math.floor(dd/(60*60*1000*24)*1);
        dhour=Math.floor((dd%(60*60*1000*24))/(60*60*1000)*1);

        if(0<dhour && dhour<10){dhour="0"+dhour;}
        dmin=Math.floor(((dd%(60*60*1000*24))%(60*60*1000))/(60*1000)*1);
        if(0<dmin && dmin<10){dmin="0"+dmin;}
        dsec=Math.floor((((dd%(60*60*1000*24))%(60*60*1000))%(60*1000))/1000*1);
        if(0<dsec && dsec<10){dsec = "0"+dsec;}

        if(dday<=0 && dhour<=0&&dmin<=0&&dsec<=1&&todayd==da){
            document.getElementById(id).innerHTML='';
            return;
        }else if (dday<=-1){
            document.getElementById(id).innerHTML="";
            return;
        }else{
            var countdown_html = '';
            if(dday>0){
                countdown_html = '<span class="dday">'+dday+'</span>';
                countdown_html +='<span class="text_day">'+textday+'</span>';
            }
            countdown_html  +=  '<span class="dhour">'+dhour+'</span>'+
                '<span class="dmin">'+dmin+'</span>'+
                '<span class="dsec">'+dsec+'</span>';
            document.getElementById(id).innerHTML = countdown_html;
            setTimeout(function(){countdown(textday,id,yr,mo,da,ho,mi,se);},1000);
        }
    }
</script>