How to cancel the paid orders?
We understand that ordering an item for your special occasion is an important undertaking. However, it is important to note that our dresses are made to order. Once the tailoring process has begun, the materials cannot be reused.

The good news is that after placing your order, there is still time to change your mind. Please refer to our cancellation policy below for details

Our Cancellation Policy for Dresses:
1. Orders cancelled within 12 hours of payment confirmation will be eligible for a full refund.
2. Orders cancelled 12 - 24 hours after payment confirmation will be eligible for a partial refund including the full shipping cost and 50% of the product purchase price.
3. Orders cancelled 24 - 48 hours after payment confirmation will be eligible for a partial refund including the full shipping cost and 30% of the product purchase price.
4. Orders cancelled after 48 hours of payment confirmation will be eligible for the full shipping cost refund only.
5. Once your order has been shipped, it can no longer be cancelled..

If you insist on cancelling the order, please submit your order number and contact our customer service staff at @.

