<p>
    Email: To send us a message, please complete the fields below. We will research your request and respond in 24-48 hours. Or you can please contact us at services@beingformal.com.au. If you do not receive a reply in your inbox, please check your spam filter or junk folder for an email from our customer service team.

</p>

<?php echo $this->getLayout()->createBlock('core/template')->setComeFrom('helpcenter')->setTemplate('contacts/form.phtml')->toHtml(); ?>
