Once you start shopping for wedding dress, party dress, you'll hear a lot of the fabric terms — satin, charmeuse, chiffon, Organza, tulle, lace, silk, Chantilly, ... But unless you are a seamstress or related staff, you may not know exactly what they mean and, more importantly, which one will make a better choice for your dream dress.
We consulted several related staff to help us know the specific words of bridal wear and distinguish between them and give you the lowdown on how they wear.

Satin

One of the most common, most versatile, and most durable bridal fabrics, satin has a smooth finish with a lot of body, making it perfect for more structured gowns. It's a supportive fabric that works with every body type and is a good choice for ruched, draped, and ball gown styles. And because it tends to be a thicker fabric, it's also a good choice for cooler weather weddings, particularly duchess satin. Most bridal satins tend to be 100 percent silk.

Charmeuse

Usually silk, but also synthetic, charmeuse is a light, rich fabric with a lovely drape and a glossy sheen. "Charmeuse has a gorgeous liquid effect that's slinky, but it's not so forgiving," says Hall. Most often cut on the bias (diagonally across the grain to encourage it's drape) and used in column dresses, charmeuse is incredibly luxurious, but it does show every flaw.

Chiffon

Incredibly sheer and lightweight, chiffon is a light woven fabric. Because it's so sheer, it's often used in layers or as an overlay for a more substantial fabric. This delicate fabric has a floaty, weightless look, but it does fray and snag easily.

Organza

Like chiffon, organza is a sheer, lightweight woven, but far stiffer than chiffon. Whereas chiffon drapes, organza is more structured, though still light and ethereal, making it perfect for warmer weather weddings. It, too, is a very delicate fabric, so watch out for snags and pulls.
See More: Browse Hundreds of Ideas for a Summer Wedding

Tulle

You know the light, netlike fabric that ballerina's tutus are made of? That's tulle. Tulle is sheer with on open weave that looks like netting. The fabric can incorporate lace designs, as well. According to Hall, a ball gown style made of tulle will have a diaphanous, airy feeling, but ruching it will give it more structure. Either way, it's an incredibly delicate fabric, easily snagged on jewelry.

Lace

Most often used as an overlay or detail, lace comes in a startling variety of styles, most often named for the city where they were originally produced. Some of the more popular varieties are Chantilly (a very detailed, open lace with a defined border), Alençon (bold motifs on net, trimmed with cord), and Venise (heavier and more textured; often used in winter weddings). As with tulle, the open weave makes it susceptible to snags.

Our experts are also seeing other fabrics gain popularity in wedding wear, such as mikado (a heavy silk), gazar (crisp and smooth), and radzmir (firm and lustrous). Other hot trends, according to Hall, include creative and artistic tattoo and laser-cut laces, which nod to the traditional while still being fresh and modern.
