<h4>Main shipping methods</h4>



<p>
    <br/>
    <br/>
    <h5>Expedited shipping</h5>
    Delivery time is between 2 - 5 days to all major destinations if it can ship to your country directly. Different items have different shipping costs, but all expedited shipping order will get a 50% discount on shipping costs.
</p>





<p>
    <br/>
    <br/>
    <h5>Standard shipping</h5>
    Delivery time is between 4 - 8 days to all major destinations, standard shipping costs less but takes a bit longer than expedited shipping. 
</p>


<p>
    <br/>
    <br/>
    Note: The above estimated delivery time is just shipping time, not time for making your dress.
</p>
