<p>
    Beingformal makes it easy paying for your orders by providing a range of convenient payment options. Below is a guide to the different payment methods used by us, so that you can choose the right way for you.
</p>


<p>
    <h4>Paying with Credit Cards</h4>

    Pay by Credit Card is easy and fast. You can pay by Credit/Debit Cards directly. It is safe and fast.
</p>


<p>
    <h4>Paying with Paypal</h4>

    PayPal is a safer, easier way to send and receive money online. It enables you to make payments quickly and securely online by using a credit card or bank account. When you select PayPal as the payment method, you will be connected to the PayPal site where you make the payment.
    <br>

    PayPal can be used here to purchase items by Credit Card (Visa, MasterCard, Discover, and American Express),Debit Card, or E-check.
    <br>
    1. After viewing your items on your shopping cart page, you can click check out with PayPal, then you will leave the shopping cart page, enter into the page of PayPal directly. Or you can click Proceed to Pay, you can fill out your billing info and choose shipping method.
    <br>
    According to the on-screen instructions, you can use the PayPal as you want.
    <br>
    You must be very alert towards possible fraud sites purporting to be the real PayPal site. The fraud sites are always 'fishing', and you can’t click on links to "PayPal verification" emails. 
</p>