<p>
    <h4>1. When will I receive my items</h4>
    This dress are Made-To-Order. Shipping time varies depending on where you're located. The earliest arrival date will be within 7 days if order placed TODAY. 
    <br>
    Items in stock will be shipped out in 24-72 hours. Items not in stock take longer to process and the time frame differs according to categories.





    <h4>Some unavoidable reasons:</h4>
    We will ship out the item according to your requests, but we can not assure you exactly how many days you can receive this item. There are many factors that may cause the delay of your item, e.g. holiday season, bad weather conditions, strikes as well as conflict, etc.
    <br>
    But we will ship it out before the shipping deadline, and try our best to negotiate with the related shipping company and ask them to take your case as priority.

</p>





<p>
    <h4>2. How much does the shipping cost?</h4>

    The shipping rates can be previewed on beingformal.com.au. By clicking on the "Estimated shipping Costs" and choose the country you want to ship to, shipping fees can be automatically estimated.
</p>


<p>
    <h4>3. If the items are detained by customs, who is responsible for clearance of the items?</h4>
    If the items are detained by Customs after the ship left the seller's country, the buyer is responsible for clearance of the detained items.
</p>