<dl class="sizechard"><dt><strong>Regular Sizing</strong></dt><dd>
<table class="wedtable" style="width: 780px;" border="0">
<tbody>
<tr><th colspan="17">Dress Size Chart</th></tr>
<tr>
<td class="wedtdbg">US Size</td>
<td colspan="2">2</td>
<td colspan="2">4</td>
<td colspan="2">6</td>
<td colspan="2">8</td>
<td colspan="2">10</td>
<td colspan="2">12</td>
<td colspan="2">14</td>
<td colspan="2">16</td>
</tr>
<tr>
<td class="wedtdbg">Europe Size</td>
<td colspan="2">32</td>
<td colspan="2">34</td>
<td colspan="2">36</td>
<td colspan="2">38</td>
<td colspan="2">40</td>
<td colspan="2">42</td>
<td colspan="2">44</td>
<td colspan="2">46</td>
</tr>
<tr>
<td class="wedtdbg">UK Size</td>
<td colspan="2">6</td>
<td colspan="2">8</td>
<td colspan="2">10</td>
<td colspan="2">12</td>
<td colspan="2">14</td>
<td colspan="2">16</td>
<td colspan="2">18</td>
<td colspan="2">20</td>
</tr>
<tr>
<td class="wedtdbg">&nbsp;</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
</tr>
<tr>
<td class="wedtdbg">Bust</td>
<td>32.5</td>
<td>83</td>
<td>33.5</td>
<td>85</td>
<td>34.5</td>
<td>88</td>
<td>35.5</td>
<td>90</td>
<td>36.5</td>
<td>93</td>
<td>38</td>
<td>97</td>
<td>39.5</td>
<td>100</td>
<td>41</td>
<td>104</td>
</tr>
<tr>
<td class="wedtdbg">Waist</td>
<td>25.5</td>
<td>65</td>
<td>26.5</td>
<td>68</td>
<td>27.5</td>
<td>70</td>
<td>28.5</td>
<td>72</td>
<td>29.5</td>
<td>75</td>
<td>31</td>
<td>79</td>
<td>32.5</td>
<td>83</td>
<td>34</td>
<td>86</td>
</tr>
<tr>
<td class="wedtdbg">Hips</td>
<td>35.75</td>
<td>91</td>
<td>36.75</td>
<td>92</td>
<td>37.75</td>
<td>96</td>
<td>38.75</td>
<td>98</td>
<td>39.75</td>
<td>101</td>
<td>41.25</td>
<td>105</td>
<td>42.75</td>
<td>109</td>
<td>44.25</td>
<td>112</td>
</tr>
<tr>
<td class="wedtdbg">Hollow to Floor</td>
<td>58</td>
<td>147</td>
<td>58</td>
<td>147</td>
<td>59</td>
<td>150</td>
<td>59</td>
<td>150</td>
<td>60</td>
<td>152</td>
<td>60</td>
<td>152</td>
<td>61</td>
<td>155</td>
<td>61</td>
<td>155</td>
</tr>
<tr>
<td class="wedtdbg">Shoulder</td>
<td>14 4/7</td>
<td>37</td>
<td>15</td>
<td>38</td>
<td>15</td>
<td>38</td>
<td>15 1/3</td>
<td>39</td>
<td>15 3/4</td>
<td>40</td>
<td>16 1/7</td>
<td>41</td>
<td>16 1/2</td>
<td>42</td>
<td>17</td>
<td>43</td>
</tr>
<tr>
<td class="wedtdbg">Arm Length</td>
<td>18</td>
<td>45 1/2</td>
<td>18</td>
<td>45 1/2</td>
<td>18</td>
<td>45 1/2</td>
<td>18</td>
<td>45 1/2</td>
<td>18</td>
<td>45 1/2</td>
<td>18</td>
<td>45 1/2</td>
<td>18</td>
<td>45 1/2</td>
<td>18</td>
<td>45 1/2</td>
</tr>
<tr>
<td class="wedtdbg">Armscye</td>
<td>15</td>
<td>38</td>
<td>15 1/3</td>
<td>39</td>
<td>16</td>
<td>40 1/2</td>
<td>16 1/3</td>
<td>41 1/2</td>
<td>16 3/4</td>
<td>42 1/2</td>
<td>17 1/3</td>
<td>44</td>
<td>18</td>
<td>45 1/2</td>
<td>18 1/2</td>
<td>47</td>
</tr>
</tbody>
</table>
</dd></dl><dl class="sizechard"><dt><strong>Plus Sizing</strong></dt><dd>
<table class="wedtable" style="width: 780px;" border="0">
<tbody>
<tr><th colspan="15">Plus Size Dress Size Chart</th></tr>
<tr>
<td class="wedtdbg">Plus Size (US)</td>
<td colspan="2">14W</td>
<td colspan="2">16W</td>
<td colspan="2">18W</td>
<td colspan="2">20W</td>
<td colspan="2">22W</td>
<td colspan="2">24W</td>
<td colspan="2">26W</td>
</tr>
<tr>
<td class="wedtdbg">Europe Size</td>
<td colspan="2">44</td>
<td colspan="2">46</td>
<td colspan="2">48</td>
<td colspan="2">50</td>
<td colspan="2">52</td>
<td colspan="2">54</td>
<td colspan="2">56</td>
</tr>
<tr>
<td class="wedtdbg">UK Size</td>
<td colspan="2">18</td>
<td colspan="2">20</td>
<td colspan="2">22</td>
<td colspan="2">24</td>
<td colspan="2">26</td>
<td colspan="2">28</td>
<td colspan="2">30</td>
</tr>
<tr>
<td class="wedtdbg">&nbsp;</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
<td>inch</td>
<td>cm</td>
</tr>
<tr>
<td class="wedtdbg">Bust</td>
<td>41</td>
<td>104</td>
<td>43</td>
<td>109</td>
<td>45</td>
<td>114</td>
<td>47</td>
<td>119</td>
<td>49</td>
<td>124</td>
<td>51</td>
<td>130</td>
<td>53</td>
<td>135</td>
</tr>
<tr>
<td class="wedtdbg">Waist</td>
<td>34</td>
<td>86</td>
<td>36.25</td>
<td>92</td>
<td>38.5</td>
<td>98</td>
<td>40.75</td>
<td>104</td>
<td>43</td>
<td>109</td>
<td>45.25</td>
<td>115</td>
<td>47.5</td>
<td>121</td>
</tr>
<tr>
<td class="wedtdbg">Hips</td>
<td>43.5</td>
<td>110</td>
<td>45.5</td>
<td>116</td>
<td>47.5</td>
<td>121</td>
<td>49.5</td>
<td>126</td>
<td>51.5</td>
<td>131</td>
<td>53.5</td>
<td>136</td>
<td>55.5</td>
<td>141</td>
</tr>
<tr>
<td class="wedtdbg">Hollow to Floor</td>
<td>61</td>
<td>155</td>
<td>61</td>
<td>155</td>
<td>61</td>
<td>155</td>
<td>61</td>
<td>155</td>
<td>61</td>
<td>155</td>
<td>61</td>
<td>155</td>
<td>61</td>
<td>155</td>
</tr>
<tr>
<td class="wedtdbg">Shoulder</td>
<td>17 1/3</td>
<td>44</td>
<td>17 5/7</td>
<td>45</td>
<td>18 1/9</td>
<td>46</td>
<td>18 1/2</td>
<td>47</td>
<td>18 8/9</td>
<td>48</td>
<td>18 8/9</td>
<td>48</td>
<td>19 2/7</td>
<td>49</td>
</tr>
<tr>
<td class="wedtdbg">Arm Length</td>
<td>18</td>
<td>45 1/2</td>
<td>18</td>
<td>45 1/2</td>
<td>18 1/2</td>
<td>47</td>
<td>19</td>
<td>48 1/2</td>
<td>19</td>
<td>48 1/2</td>
<td>19 1/2</td>
<td>49</td>
<td>19 1/2</td>
<td>49 1/2</td>
</tr>
<tr>
<td class="wedtdbg">Armscye</td>
<td>18 5/7</td>
<td>47 1/2</td>
<td>19 2/7</td>
<td>49</td>
<td>20 1/2</td>
<td>52</td>
<td>20 2/3</td>
<td>52 1/2</td>
<td>20 4/5</td>
<td>52 4/5</td>
<td>21 2/5</td>
<td>54 1/2</td>
<td>21 1/2</td>
<td>54 3/5</td>
</tr>
</tbody>
</table>
</dd></dl>