
<p>
    <h4>Place for Fashionista & Bloggers</h4>
    <br>
    Are you a fashionista? Do you love to share the news to your friends? If so, you are the guy whom we are looking for! How to be one members of us? You can send us a brief introduction of blog, for example, who you are, where are you from, why you like us and your blog name. 
    <br>
    What you can get from us. We will email you back. 
    <br>
</p>



<p>
    Qualification to become a member of Beingformal.com.au Fashion Blogger Program:
    <br>
    -Established Blogger or a "power user and opinion leader" on Facebook or Lookbook or other fashion blog communities (Fashiolista, Blogher, and so on).
    <br>
    -Blog theme is about women fashion. Love fashion trend and could catch up with the latest fashion trend
    <br>
    -Your blog is active and at least have over 800 members or subscribers, and also you have a social network of more than 1000 fans 
    <br>
</p>


<p>
    If you do not have those qualifications but you think you surely are an opinion leader, you could also have a try.
    <br>

    Join us now! 
</p>