<h4>VIP Levels and Discounts</h4>


<p>
    <h4>How to become a VIP member?</h4>

    No minimum consumption is required to join the program !
    <br>
    <h4>Step 1: Make an order successfully (no minimum consumption).</h4>
    <br>
    <h4>Step 2: Enjoy VIP discounts on your very next order.</h4>
    <br>

    VIP Program aims to offer amazing shopping experience and exclusive discounts to our customers. Buy more, and save more!

    <br>
    VIP Discount
    <br>
    There are three levels of VIP membership, and each level enjoys different discounts. VIP level is determined by cumulative amount .(Shipping fee is not included)
    <br>

    Our system will upgrade your membership level according to the cumulative amount(shipping fee not included) spent at our website and we will inform you by email in case of the membership upgrade. At least one order has to be made per year. Otherwise your membership level will be downgraded to the lower one. 
    <br>

    <h4>3.If unfortunately your VIP level is downgraded, you can still enjoy the privileges of the new level and you may re-upgrade to your former level by simply making a new order.</h4>
</p>



<p>
    <h4>Notes:</h4>
    <br>
    VIP discounts rank first in the presence of any other preferential policies offered at beingformal.com.au
    <br>
    2.If refund is requested, the refunded amount will be deducted from the total cumulative amount.
    <br>

    If you have any questions, please feel free to contact our customer service.
    <br>
    Email: service@tbdress.com
    <br>
    Phone: +86-29-68532816
    <br>
    VIP: +86-29-68968081
    <br>
</p>