<?php $_option = $this->getOption() ?>
<dt class="<?php echo  $this->escapeHtml($_option->getTitle()) ?>">
    <label<?php if ($_option->getIsRequire()) echo ' class="required"' ?>><?php echo  $this->escapeHtml($_option->getTitle()) ?>:</label></dt>
<dd class="<?php echo  $this->escapeHtml($_option->getTitle()) ?>">
    <div class="input-box">
        <?php echo $this->getValuesHtml() ?>
        <?php if ($_option->getIsRequire()): ?>
            <?php if ($_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_RADIO || $_option->getType() == Mage_Catalog_Model_Product_Option::OPTION_TYPE_CHECKBOX): ?>
                <span id="options-<?php echo $_option->getId() ?>-container"></span>
            <?php endif; ?>
        <?php endif;?>
    </div>
</dd>
