<?php if($this->getComeFrom() != 'helpcenter'):?>

    <table class="helpcenter">
        <tr>
            <td class="help_left">
                <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('cms/helpcenter/a_left.phtml')->toHtml(); ?>
            </td>
            <td class="help_right">
<?php endif;?>
                    <div class="contacts">
                        <div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>



                        <div class="page-title">
                            <h1><?php echo Mage::helper('contacts')->__('Contact Us') ?></h1>
                        </div>






                        <form action="/contacts/index/post/" id="contactForm" method="post">
                            <div class="fieldset">
                                <ul class="form-list">
                                    <li class="fields">
                                        <div class="field">
                                            <label for="name" class="required"><?php echo Mage::helper('contacts')->__('Name') ?>:<em>*</em></label>
                                            <div class="input-box">
                                                <input name="name" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Name')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                                            </div>
                                        </div>
                                        <div class="field">
                                            <label for="email" class="required"><?php echo Mage::helper('contacts')->__('Email') ?>:<em>*</em></label>
                                            <div class="input-box">
                                                <input name="email" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Email')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <label for="telephone"><?php echo Mage::helper('contacts')->__('Telephone') ?>:</label>
                                        <div class="input-box">
                                            <input name="telephone" id="telephone" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Telephone')) ?>" value="" class="input-text" type="text" />
                                        </div>
                                    </li>
                                    <li class="wide">
                                        <label for="comment" class="required"><?php echo Mage::helper('contacts')->__('Comment') ?>:<em>*</em></label>
                                        <div class="input-box">
                                            <textarea name="comment" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Comment')) ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                            <div class="buttons-set">
                                <!-- <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p> -->
                                <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
                                <button type="button"  class="button" style="float:left;" onClick="window.history.back();"><span><span>Back</span></span></button>

                                <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Submit')) ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('Submit') ?></span></span></button>
                            </div>
                        </form>



                        <script type="text/javascript">
                        //<![CDATA[
                            var contactForm = new VarienForm('contactForm', true);
                        //]]>
                        </script>
                    </div>
<?php if($this->getComeFrom() != 'helpcenter'):?> 
            </td>
        </tr>
    </table>
<?php endif;?>



                    