<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
?>



<?php if(!$_productCollection->count()): ?>
    <p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>

    <div class="category-products">

        <div class="category-products-header">   
            <p class="products-count">We found <span><?php echo $_productCollection->getSize();?></span> items 
                <?php $current_category = Mage::registry('current_category');?>
                <?php if(isset($current_category)):?>
                    of <?php echo $current_category->getName()?> !
                <?php endif;?>
            </p>
                
            <?php echo $this->getLayout()->createBlock('catalog/product_list_toolbar')
                            ->setTemplate('catalog/product/list/sort.phtml')
                            ->setName('sort')
                            ->toHtml(); ?>
        </div>

       
       
        <ul class="products-grid">
            <?php foreach ($_productCollection as $_product): ?>
                <li class="item">
                    <?php echo $this->getLayout()->createBlock('catalog/product_list')
                                    ->setProduct($_product)
                                    ->setShowName('show')
                                    ->setPClassName('product-name-2')
                                    ->setShowCurrencyCode('show')
                                    ->setTemplate('page/pub/product_card.phtml')->toHtml(); ?>
                    
                    <?php if($_product->getRatingSummary()): ?>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    <?php endif; ?>
                </li>
            <?php endforeach ?>
        </ul>
        

        <div class="toolbar-bottom">
            <?php echo $this->getToolbarHtml() ?>
        </div>


    </div>

<?php endif; ?>