<?php $_helper = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>




<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>



<script type="text/javascript" data-name="product-price">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>



<div class="product-view">
    <div class="pLeft">
        <p class="website_name">beingformal</p>
        <p class="service">
            <a href="/helpcenter/size_chart.html">size chart</a>
            <a href="">color chart</a>
            <a href="">return policy</a>
        </p>
        <p class="interaction">
            <a href="?r#review-form" class="write-a-review">write a review</a> 
            <a href="?f#faq-form" class="ask-a-question">ask a question</a>
        </p>
        <?php $fabric_links = Mage::getModel('ibanners/group')->loadByCode('fabric_link')->getBannerCollection();?>
        <?php if(count($fabric_links)):?>
            <?php foreach($fabric_links as $banner):?>
                <?php
                    $cat_ids = $banner->getHtml();
                    $product_cat_ids = $_product->getCategoryIds();
                    $result=array_intersect(explode(",", $cat_ids ),$product_cat_ids);
                ?>
                <?php if(count($result)):?>
                    <p class="fabric_link"><a class="item" href="<?php echo $banner->getUrl()?>"><img src="<?php echo $banner->getImageUrl()?>"></a></p>
                <?php endif;?>
            <?php endforeach;?>
        <?php endif;?>

        <?php echo $this->getChildHtml('catalog.product.related');?>
    </div>
    <div class="pRight">
        <form action="<?php echo $this->getSubmitUrl($_product, array('_secure' => $this->_isSecure())) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
            <?php echo $this->getBlockHtml('formkey') ?>
            <div class="no-display">
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                <input type="hidden" name="related_product" id="related-products-field" value="" />
            </div>

            <?php echo $this->getPriceHtml($_product) ?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>

            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php if($_product->isSaleable()): ?>
                        <?php echo $this->getChildHtml('addtocart') ?>
                        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                            <span class="or"><?php echo $this->__('OR') ?></span>
                        <?php endif; ?>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php elseif (!$_product->isSaleable()): ?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addto') ?>
                </div>
            <?php endif; ?>

        </form>
        <script type="text/javascript" data-name="添加购物车">
            //<![CDATA[
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function(button, url) {
                    if (this.validator.validate()) {
                        var form = this.form;
                        var oldUrl = form.action;

                        if (url) {
                           form.action = url;
                        }
                        var e = null;
                        try {
                            this.form.submit();
                        } catch (e) {
                        }
                        this.form.action = oldUrl;
                        if (e) {
                            throw e;
                        }

                        if (button && button != 'undefined') {
                            button.disabled = true;
                        }
                    }
                }.bind(productAddToCartForm);

                productAddToCartForm.submitLight = function(button, url){
                    if(this.validator) {
                        var nv = Validation.methods;
                        delete Validation.methods['required-entry'];
                        delete Validation.methods['validate-one-required'];
                        delete Validation.methods['validate-one-required-by-name'];
                        // Remove custom datetime validators
                        for (var methodName in Validation.methods) {
                            if (methodName.match(/^validate-datetime-.*/i)) {
                                delete Validation.methods[methodName];
                            }
                        }

                        if (this.validator.validate()) {
                            if (url) {
                                this.form.action = url;
                            }
                            this.form.submit();
                        }
                        Object.extend(Validation.methods, nv);
                    }
                }.bind(productAddToCartForm);
            //]]>
            </script>
    </div>
    <div class="pMain">
        <div class="product-header">
            <div class="share">SHARE:</div>
            <div class="product-sku">SKU <?php echo $_helper->productAttribute($_product, $_product->getSku(), 'sku') ?></div>
        </div>

        <div class="prodoct-datail">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>

            <div class="count-review">
                <span class="xin">
                    <span class="count">
                        242
                    </span>
                </span>
            </div>

            <div class="product-img-box">
                <!-- 大图 -->
                <?php
                    $getGalleryImages = $this->getProduct()->getMediaGalleryImages();
                    if(count($getGalleryImages) > 0){
                        foreach ($getGalleryImages as $_image){
                            $big_img_src = $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(600,800);
                            break;
                        }
                    }
                ?>
                <div id="w-featurePics">
                    <a target="_blank" href="<?php echo $big_img_src;?>" title="">
                        <img src="<?php echo $big_img_src;?>" alt="">
                    </a>
                </div>
                <?php echo $this->getChildHtml('media') ?>
            </div>
        </div>

        <!-- 缩略图 -->
        <?php if(count($getGalleryImages) > 0): ?>
            <div id="prodthumbnails">
                <div id="productImages">
                    <div class="toleft"></div>
                    <div class="thumbnails">
                        <ul>
                            <?php $i=0; foreach ($getGalleryImages as $_image): ?>
                                <li <?php if($i==0){echo 'class="active"';}$i++;?> >
                                    <input  type="hidden" 
                                        data-image="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(600,800); ?>" 
                                        data-thumb="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(66,88); ?>">
                                    <a>
                                        <img    src="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(66,88); ?>"
                                                data-imgpath="<?php echo $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(600,800); ?>" />
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <div class="toright"></div>
                </div>
            </div>
        <?php endif; ?>
    </div>

    <!-- 选项卡部分:产品详情，review，FAQ,HOW TO WASH -->
    <div class="product-TABS">
        <script type="text/javascript" data-name="选项卡切换">
            jQuery(document).ready(function($){
                //选项卡切换
                $('.product-TABS>ul li').click(function(){
                    $('.product-TABS>ul li').removeClass('active');
                    $(this).addClass('active');
                    $('.product-TABS .tabs>div').removeClass('active');
                    $('.tab-'+$(this).attr('id')).addClass('active');
                });
                //锚点切换
                if(window.location.hash === '#review-form' || window.location.hash === '#faq-form'){
                    $('.product-TABS .tabs>div').removeClass('active');
                    $(window.location.hash).parent().addClass('active');
                    var active_index = $(window.location.hash).parent().index();
                    $('.product-TABS>ul li').removeClass('active');
                    $('.product-TABS>ul li').eq(active_index).addClass('active');
                }
            });
        </script>
        <ul>
            <li id="descriptions" class="active">Descriptions</li>
            <li id="reviews">Reviews</li>
            <li id="faqs">FAQs</li>
            <li id="how_to_wash">How to Wash</li>
        </ul>
        <div class="tabs">
            <div class="tab-descriptions active">
                <?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
                    <div class="box-collateral <?php echo "box-{$alias}"?>">
                        <?php if ($title = $this->getChildData($alias, 'title')):?>
                        <h2><?php echo $this->escapeHtml($title); ?></h2>
                        <?php endif;?>
                        <?php echo $html; ?>
                    </div>
                <?php endforeach;?>
            </div>
            <div class="tab-reviews">
                <?php echo $this->getChildHtml('product_review');?>
            </div>
            <div class="tab-faqs">
                <?php echo $this->getChildHtml('askquestions');?>
            </div>
            <div class="tab-how_to_wash"></div>
        <div>
    </div>
</div>





















    

           

            
<?php /**
        <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
        <?php echo $this->getChildHtml('alert_urls') ?>
        <?php echo $this->getChildHtml('product_type_data') ?>
        <?php echo $this->getTierPriceHtml() ?>
        <?php echo $this->getChildHtml('extrahint') ?>
        <?php echo $this->getChildHtml('other');?>
        <?php if ($_product->isSaleable() && $this->hasOptions()):?>
            <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
        <?php endif;?>
        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
**/?>