<div class="content-header">
   <h3 class="icon-head"><?php echo $this->getHeaderText() ?></h3>
   <p class="content-buttons form-buttons">
        <?php echo $this->getBackButtonHtml(); ?>
        <?php echo $this->getResetButtonHtml(); ?>
        <?php echo $this->getSaveButtonHtml(); ?>
        <?php echo $this->getContinueButtonHtml(); ?>
    </p>
</div>
<form action="<?php echo $this->getSaveUrl(); ?>" method="post" id="tags_form">
	<div class="no-display">
		<input type="hidden" id="continue" name="continue" value="" />
	</div>
	<?php echo $this->getForm(); ?>
</form>
<script type="text/javascript">
//<![CDATA[
    var categoryForm = new varienForm('tags_form');
    var categoryControl  = {
    	save: function() {
    		categoryForm.submit();
            return false;
    	},
    	continue: function() {
    		$('continue').writeAttribute('value',1);
    		categoryForm.submit();
            return false;
    	}
    }
//]]>
</script>