<?php if($this->getCollection()->getSize()): ?>
    <?php if($this->getLastPageNum()>1): ?>
        <?php
            $p_request = $this->getRequest()->getParam('p');
            $p_request = $p_request?$p_request:1;
            $p_array = $this->getFramePages();
        ?>
        <div class="pagination">
            <ol>
                <?php if (!$this->isFirstPage()): ?>
                <li><a class="previous" href="<?php echo $this->getPreviousPageUrl() ?>">&nbsp;</a></li>
                <?php endif;?>

                <?php if ($p_request && $p_request>5 && $p_array[0]!=1): ?>
                <li><a href="<?php echo $this->getFirstPageUrl() ?>">1</a></li>
                <li class="dian">...</li>
                <?php endif?>

                <?php foreach ($this->getFramePages() as $_page): ?>
                    <?php if ($this->isPageCurrent($_page)): ?>
                        <li class="current"><?php echo $_page ?></li>
                    <?php else: ?>
                        <li><a href="<?php echo $this->getPageUrl($_page) ?>"><?php echo $_page ?></a></li>
                    <?php endif;?>
                <?php endforeach;?>

                <?php if ($p_request && $p_request<$this->getLastPageNum()-3 && end($p_array)!=$this->getLastPageNum()): ?>
                    <li class="dian">...</li>
                    <li><a href="<?php echo $this->getLastPageUrl() ?>"><?php echo $this->getLastPageNum() ?></a></li>
                <?php endif;?>


                <?php if (!$this->isLastPage()): ?>
                    <li><a class="next" href="<?php echo $this->getNextPageUrl() ?>">&nbsp;</a></li>
                <?php endif;?>
            </ol>
        </div>
    <?php endif; ?>
<?php endif ?>
