<?php /*
        排序选项为：
        Recommened (按照产品评论的个数排列，评论数最多的显示在最前面，若果评论数相同，则价格低的显示在最前面。)
        new arrival ,
        low price,
        high price,
        discount (按照折扣高的排列，同样折扣则价格低的显示在前面)
    */?>

<div class="products-sort">
    <label>SORT BY</label>
    <ul>
        <li <?php if($this->isOrderCurrent('recommened')){echo 'class="selected"';}?>>
            <a href="<?php echo $this->getOrderUrl('recommened', 'desc') ?>">recommened</a>
        </li>
        <li <?php if($this->isOrderCurrent('news_from_date')){echo 'class="selected"';}?>>
            <a href="<?php echo $this->getOrderUrl('news_from_date', 'desc') ?>">new arrival</a>
        </li>
        <li <?php if($this->isOrderCurrent('price') && $this->getCurrentDirection()=='asc'){echo 'class="selected"';}?>>
            <a href="<?php echo $this->getOrderUrl('price', 'asc') ?>">low price</a>
        </li>
        <li <?php if($this->isOrderCurrent('price') && $this->getCurrentDirection()=='desc' ){echo 'class="selected"';}?>>
            <a href="<?php echo $this->getOrderUrl('price', 'desc') ?>">high price</a>
        </li>
        <li <?php if($this->isOrderCurrent('discount')){echo 'class="selected"';}?>>
            <a href="<?php echo $this->getOrderUrl('discount', 'asc') ?>">discount</a>
        </li>


        <?php /*
        <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
            <?php if($this->isOrderCurrent($_key)): ?>
                <li  class="selected">
                    <?php echo $_order;?>
                </li>
            <?php else:?>
                <li>
                    <a href="<?php echo $this->getOrderUrl($_key, 'desc') ?>"><?php echo $_order;?></a>
                </li>
            <?php endif; ?>
        <?php endforeach;?>
        */?>
    </ul>
    
</div>
