
<div class="products-sort">
    SORT BY

    <ul>
        <?php foreach($this->getAvailableOrders() as $_key=>$_order): ?>
            <?php if($this->isOrderCurrent($_key)): ?>
                <li  class="selected">
                    <?php echo $_order;?>
                </li>
            <?php else:?>
                <li>
                    <a href="<?php echo $this->getOrderUrl($_key, 'desc') ?>"><?php echo $_order;?></a>
                </li>
            <?php endif; ?>
        <?php endforeach;?>
    </ul>
    
</div>
