<?php

$helper = Mage::helper('itags');
$alphabet = $helper->getAlphabet(); 
$w = $this->getRequest()->getParam('w');
?>
<div class="itags-alphabet">
	<?php $i = 0; ?>
	<?php foreach($alphabet as $letter): ?>
	   <?php if($i!=0): ?>&nbsp;|&nbsp;<?php endif; ?>
	   <a title="<?php echo $letter; ?>" href="<?php echo $helper->getLetterUrl($letter); ?>"><?php echo $letter; ?></a>
	   <?php $i++; ?>
	<?php endforeach; ?>
</div>


<div class="itags-list">
    <?php $tags = $this->getTags(); ?>
    <?php if(count($tags)): ?>
        <ul>
        <?php foreach ($tags as $_tag): ?>
        	<li><a href="<?php echo strtolower($helper->getProductListUrl($_tag->getTagsText())); ?>"><?php echo $this->htmlEscape($_tag->getTagsText()); ?></a>
        <?php endforeach; ?>
        </ul>
    	
    <?php else: ?>
        <p class="note-msg"><?php echo $this->__('No tag available.') ?></p>
    <?php endif; ?>
</div>


<br class="clear" />


<div class="itags-pager">
<?php echo $this->getPagerHtml(); ?>
</div>
