<?php $productListBlock = Mage::getBlockSingleton('catalog/product_list'); ?>
<?php $_helper = $this->helper('catalog/output'); ?>
<?php $helper = Mage::helper('itags'); ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="page-title">
	<?php $q = $this->helper('catalogsearch')->getEscapedQueryText(); ?>
    <?php if ($this->helper('rss/catalog')->getTagFeedUrl()): ?>
        <a href="<?php echo $this->helper('rss/catalog')->getTagFeedUrl() ?>" class="nobr link-rss"><?php echo $this->__('Subscribe to Feed') ?></a>
    <?php endif; ?>
    <h1><?php echo $q; ?></h1>
    <p><?php echo str_ireplace($q,"<strong>".$q."</strong>",$this->getDescription()); ?></p>
</div>
<div class="icategory-banner">
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('icategory-banner')->toHtml() ?>
</div>
ddd
<div class="category-products">
<?php $resultEmpty = true; ?>
<?php $_columnCount = 3; ?>
<?php if($helper->getViewSearchEnable()): ?>
	<?php $searchCollection = $this->getSearchCollection(); ?>
	<?php if($_collectionSize = $searchCollection->getSize()): ?>
	<?php $resultEmpty = false; ?>
	<div class="toolbar"><?php echo $this->getChildHtml('pagerSearch'); ?></div>
	<div class="grid-block">
		<?php $i=0; foreach ($searchCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>    
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(237,255); ?>" width="237" height="255" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
				<?php echo $this->getPriceHtml($_product, true) ?>
				<div class="clr"></div>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
	</div>
	<?php echo $this->getChildHtml('pagerSearch'); ?>
	<?php endif; ?>
<?php endif; ?>
<?php if ($this->getTagId() && $helper->getViewTagEnable()): ?>
    <?php $tagsCollection = $this->getTagsCollection(); ?>
    <?php if($_collectionSize = $tagsCollection->getSize()): ?>
    <br />
    <?php $resultEmpty = false; ?>
    <h2><?php echo $this->__("Products tagged with '%s'",$this->htmlEscape($this->getQueryText())); ?></h2>
    <?php echo $this->getChildHtml('pagerTags'); ?>
    <div class="grid-block">
    	<?php $i=0; foreach ($tagsCollection as $_product): ?>
        <?php if ($i++%$_columnCount==0): ?>
        <ul class="products-grid">
        <?php endif ?>    
            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(237,255); ?>" width="237" height="255" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a></h2>
				<?php echo $this->getPriceHtml($_product, true) ?>
				<div class="clr"></div>
                <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
            </li>
        <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
        </ul>
        <?php endif ?>
        <?php endforeach ?>
        <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script>
    </div>
    <div class="toolbar-bottom"><?php echo $this->getChildHtml('tagsSearch'); ?></div>
    <?php endif; ?>
<?php endif; ?>
<?php if ($resultEmpty): ?>

<div class="iempty">
	<div>
		<p>Your Search:&nbsp;<span class="red"><?php echo $q; ?></span></p>
		<h3 class="red">Sorry, your search returned no results.</h3>
		<p class="g_t_c"><a href="<?php echo Mage::getBaseUrl(); ?>" title="<?php echo Mage::helper('checkout')->__('Continue Shopping'); ?>" alt="<?php echo Mage::helper('checkout')->__('Continue Shopping'); ?>" class="icontinue"><b><?php echo Mage::helper('checkout')->__('Continue Shopping'); ?></b></a></p>
	</div>
</div>
<?php endif; ?>
<!--
<div class="i-site-search">
	<form method=get action="http://www.google.com/search">
	<input type=text name="q" value="<?php echo $q; ?>">
	<input type=submit name=btnG value="Google">
	<input type=hidden name=ie value=GB2312>
	<input type=hidden name=oe value=GB2312>
	<input type=hidden name=hl value=zh-CN>
	<input type=hidden name=domains value="<?php echo $this->getDomain(); ?>">
	<input type=hidden name=sitesearch value="<?php echo$this->getDomain(); ?>">
	</form>
</div>
-->
</div>
