<?php 
    $_product = $this->getProduct();
?>

<a  href="<?php echo $_product->getProductUrl() ?>" 
    title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"
    class="product_card item" 
    data-id="<?php echo $_product->getId()?>">




    <img    class="product-image" 
            alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" 
            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(300,400); ?>">






    <?php if($this->getShowName() == 'show'):?>
        <span class="<?php echo $this->getPClassName()?$this->getPClassName():'product-name'?>"><?php echo $_product->getName()?></span>
    <?php endif;?>






    <div class="product-price">
        <?php if($this->getShowCurrencyCode() == 'show'):?>
            <span class="currency-code"><?php echo Mage::app()->getStore()->getCurrentCurrency()->getCode();?></span>
        <?php endif;?>

        <?php echo $this->getPriceHtml($_product, true) ?>
    </div>




    <?php if($this->getCountdown() == 'show'):?>
        <?php if(time() > strtotime( $_product->getSpecialToDate() ) ):?>
            <div class="countdown-end"><?php echo str_replace('_',' ',$this->getCountdownModel() ); ?> END</div>
        <?php else:?>
            <?php if( strtotime( $_product->getspecialFromDate() ) < time() ):?>
                <div class="countdown" >
                    <div id="<?php echo $this->getCountdownModel();?>-countdown-<?php echo $_product->getId()?>"></div>
                </div>
                <script type="text/javascript" data-specialfromdate="<?php echo $_product->getspecialFromDate()?>" data-specialtodate="<?php echo $_product->getSpecialToDate()?>">
                    jQuery(document).ready(function($){
                        var $special_to_date = new Date( '<?php echo $_product->getSpecialToDate()?>' );
                        countdown(' day ',//text_day
                            '<?php echo $this->getCountdownModel();?>-countdown-<?php echo $_product->getId()?>',//id
                            $special_to_date.getFullYear(),//年
                            $special_to_date.getMonth()-0+1,//月
                            $special_to_date.getDate(),//日
                            $special_to_date.getHours(),//时
                            $special_to_date.getMinutes(),//分
                            $special_to_date.getSeconds()//秒
                            );
                    });
                </script>
            <?php endif;?>
        <?php endif;?>
    <?php endif;?>

</a>