<script type="text/javascript" data-name="尺码对照表">

    var us_obj = {
        'US2':{
            'Bust':  {'inch':32.5,'cm':83},
            'Waist': {'inch':25.5,'cm':65},
            'Hips':  {'inch':35.75,'cm':91},
            'Hollow to Floor':{'inch':58,'cm':147},

        },
        'US4':{
            'Bust':  {'inch':33.5,'cm':85},
            'Waist': {'inch':26.5,'cm':67},
            'Hips':  {'inch':36.75,'cm':93},
            'Hollow to Floor':{'inch':58,'cm':147},

        },
        'US6':{
            'Bust':  {'inch':34.5,'cm':88},
            'Waist': {'inch':27.5,'cm':70},
            'Hips':  {'inch':37.75,'cm':96},
            'Hollow to Floor':{'inch':59,'cm':150},

        },
        'US8':{
            'Bust':  {'inch':35.5,'cm':90},
            'Waist': {'inch':28.5,'cm':72},
            'Hips':  {'inch':38.75,'cm':98},
            'Hollow to Floor':{'inch':59,'cm':150},

        },
        'US10':{
            'Bust':  {'inch':36.5,'cm':93},
            'Waist': {'inch':29.5,'cm':75},
            'Hips':  {'inch':39.75,'cm':101},
            'Hollow to Floor':{'inch':60,'cm':152},

        },
        'US12':{
            'Bust':  {'inch':38,'cm':97},
            'Waist': {'inch':31,'cm':79},
            'Hips':  {'inch':41.25,'cm':105},
            'Hollow to Floor':{'inch':60,'cm':152},

        },
        'US14':{
            'Bust':  {'inch':39.25,'cm':100},
            'Waist': {'inch':32,'cm':83},
            'Hips':  {'inch':42.75,'cm':109},
            'Hollow to Floor':{'inch':61,'cm':155},

        },
        'US16':{
            'Bust':  {'inch':41,'cm':104},
            'Waist': {'inch':34,'cm':86},
            'Hips':  {'inch':44.25,'cm':112},
            'Hollow to Floor':{'inch':61,'cm':155},

        },
        'US16W':{
            'Bust':  {'inch':43,'cm':109},
            'Waist': {'inch':36.25,'cm':92},
            'Hips':  {'inch':45.5,'cm':116},
            'Hollow to Floor':{'inch':61,'cm':155},

        },
        'US18W':{
            'Bust':  {'inch':45,'cm':114},
            'Waist': {'inch':38.5,'cm':98},
            'Hips':  {'inch':47.5,'cm':121},
            'Hollow to Floor':{'inch':61,'cm':155},

        },
        'US20W':{
            'Bust':  {'inch':47,'cm':119},
            'Waist': {'inch':40.75,'cm':104},
            'Hips':  {'inch':49.5,'cm':126},
            'Hollow to Floor':{'inch':62.25,'cm':158},

        },
        'US22W':{
            'Bust':  {'inch':49,'cm':124},
            'Waist': {'inch':43,'cm':109},
            'Hips':  {'inch':51.5,'cm':131},
            'Hollow to Floor':{'inch':62.25,'cm':158},

        },
        'US24W':{
            'Bust':  {'inch':51,'cm':130},
            'Waist': {'inch':45.25,'cm':115},
            'Hips':  {'inch':53.5,'cm':136},
            'Hollow to Floor':{'inch':62.25,'cm':158},

        },
        'US26W':{
            'Bust':  {'inch':53,'cm':135},
            'Waist': {'inch':47.5,'cm':121},
            'Hips':  {'inch':55.5,'cm':141},
            'Hollow to Floor':{'inch':62.25,'cm':158},

        }
    };

</script>