<?php $helper = Mage::helper('itags'); ?>
<?php $collection = $this->getCollection(); ?>
<?php if(count($collection)): ?>
<div class="block block-related">
    <div class="block-title">
        <strong><span><?php echo $this->__('Recommended Products') ?></span></strong>
    </div>
    <div class="block-content">
        <ul class="mini-products-list" id="block-related">
        <?php foreach($collection as $_product): ?>
            <li class="item">
          			
                    <a class="product-image" title="<?php echo $this->htmlEscape($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>"><img width="50" height="50" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize(50) ?>"></a>
  <div class="product-details"><h2 class="product-name"><a title="<?php echo $this->htmlEscape($_product->getName()) ?>" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h2>
                    <?php echo $this->getPriceHtml($_product, true) ?></div>
            </li>
        <?php endforeach ?>
        </ol>
        <script type="text/javascript">decorateList('block-related', 'none-recursive')</script>
    </div>
</div>
<?php endif ?>